import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./vitest.setup.ts"],
    exclude: ["node_modules/**", "node_modulese/**", "e2e/**", ".next/**"],
    include: ["src/**/*.{test,spec}.{ts,tsx}"],
    testTimeout: 30000,
    alias: {
      "@/components": path.resolve(__dirname, "./components"),
      "@": path.resolve(__dirname, "./src"),
      "~": path.resolve(__dirname, "./"),
    },
    coverage: {
      provider: "v8",
      reporter: ["text", "text-summary"],
      include: [
        "app/**/*.{ts,tsx}",
        "src/**/*.{ts,tsx}",
        "components/**/*.{ts,tsx}",
      ],
      reportOnFailure: true,
      exclude: [
        // Generated / infra — not hand-written code
        "src/api/generated/**",
        "src/mocks/**",
        "src/test-utils/**",
        "**/*.test.{ts,tsx}",
        "**/*.spec.{ts,tsx}",
        "**/*.d.ts",
        "src/ui/**",
        // Camera/hardware dependent — requires real browser
        "app/scanner/_scanner.tsx",
        // PDF/canvas dependent — requires real browser APIs (jsPDF, canvas)
        "components/classement/BibDownloadButton.tsx",
        "components/classement/BulkBibDownloadButton.tsx",
        "components/classement/QrCodeDisplay.tsx",
        // Chakra UI scaffolded wrappers — generated by @chakra-ui/cli, no business logic
        "components/ui/color-mode.tsx",
        "components/ui/provider.tsx",
        "components/ui/tooltip.tsx",
        "components/ui/toaster.tsx",
        // MSW bootstrap — client-side service worker setup, not testable in jsdom
        "components/MswBootstrap.tsx",
        // Next.js root layout (html/body tags) — not renderable in jsdom
        "app/layout.tsx",
        // Providers entry point — imports sdk-client side-effect, creates global QueryClient
        "app/providers.tsx",
        // Thin layout wrappers — just pass-through to already-tested components
        "app/admin/layout.tsx",
        // Server-side redirect — next/navigation redirect() not testable in jsdom
        "app/admin/page.tsx",
        // SDK client setup — side-effect module (axios interceptors, baseURL config)
        "src/api/sdk-client.ts",
        // CSRF token fetcher — uses global fetch with credentials, tested via E2E
        "src/api/csrf.ts",
        // Pure constant exports (1-15 lines each, no logic, module-scope declarations)
        "src/state/**/data.ts",
        "src/state/**/schemas.ts",
        "src/state/queryKeys.ts",
      ],
    },
  },
});
