flysystem:
    storages:
        users.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'aws_s3.client'
                bucket: '%env(S3_BUCKET)%'
                prefix: 'images/users'
        race_media.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'aws_s3.client'
                bucket: '%env(S3_BUCKET)%'
                prefix: 'images/race_media'

when@test:
    flysystem:
        storages:
            users.storage:
                adapter: 'local'
                options:
                    directory: '%kernel.project_dir%/var/test-uploads/images/users'
            race_media.storage:
                adapter: 'local'
                options:
                    directory: '%kernel.project_dir%/var/test-uploads/images/race_media'
