vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        users:
            uri_prefix: '%env(S3_PUBLIC_URL)%/runner-images/images/users'
            upload_destination: users.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        race_media:
            uri_prefix: '%env(S3_PUBLIC_URL)%/runner-images/images/race_media'
            upload_destination: race_media.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
