vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        users:
            uri_prefix: '%env(S3_URL_PREFIX)%'
            upload_destination: s3_storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
