<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260328122349 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create RaceMedia table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE race_media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, runner_id INT NOT NULL, file_path VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_96B40ACF876E84C ON race_media (runner_id)');
        $this->addSql('ALTER TABLE race_media ADD CONSTRAINT FK_96B40ACF876E84C FOREIGN KEY (runner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE race_media DROP CONSTRAINT FK_96B40ACF876E84C');
        $this->addSql('DROP TABLE race_media');
    }
}
