<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260402093619 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create race_media table and fix nullable timestamps';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS race_media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) DEFAULT NULL, comment TEXT DEFAULT NULL, likes_count INT DEFAULT 0 NOT NULL, content_type VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE "user" ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER updated_at DROP NOT NULL');
        $this->addSql('ALTER TABLE run ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE run ALTER updated_at DROP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uq_user_run ON participation (user_id, run_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS race_media');
    }
}
