<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260328122349 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create race_media table with comment field';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE IF NOT EXISTS race_media (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                file_path VARCHAR(255) DEFAULT NULL,
                comment TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        // If table already existed (local dev), just add the comment column
        $this->addSql(<<<'SQL'
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'race_media' AND column_name = 'comment'
                ) THEN
                    ALTER TABLE race_media ADD comment TEXT DEFAULT NULL;
                END IF;
            END $$;
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE race_media DROP COLUMN IF EXISTS comment');
    }
}
