<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260324202210 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema + password_token + nullable timestamps';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE medias (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE participation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, arrival_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, run_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB55E24F84E3FEC4 ON participation (run_id)');
        $this->addSql('CREATE INDEX IDX_AB55E24FA76ED395 ON participation (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_user_run ON participation (user_id, run_id)');
        $this->addSql('CREATE TABLE run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE, updated_at TIMESTAMP(0) WITHOUT TIME ZONE, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5076A4C095275AB8 ON run (start_date)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5076A4C0845CBB3E ON run (end_date)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(180) NOT NULL, last_name VARCHAR(180) NOT NULL, surname VARCHAR(180) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, organization VARCHAR(180) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE, updated_at TIMESTAMP(0) WITHOUT TIME ZONE, image_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6493DA5256D ON "user" (image_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F84E3FEC4 FOREIGN KEY (run_id) REFERENCES run (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6493DA5256D FOREIGN KEY (image_id) REFERENCES medias (id)');
        $this->addSql('CREATE TABLE password_token (token VARCHAR(50) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BEAB6C245F37A13B ON password_token (token)');
        $this->addSql('CREATE INDEX IDX_BEAB6C24A76ED395 ON password_token (user_id)');
        $this->addSql('ALTER TABLE password_token ADD CONSTRAINT FK_BEAB6C24A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE password_token DROP CONSTRAINT FK_BEAB6C24A76ED395');
        $this->addSql('DROP TABLE password_token');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT FK_AB55E24F84E3FEC4');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT FK_AB55E24FA76ED395');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6493DA5256D');
        $this->addSql('DROP TABLE medias');
        $this->addSql('DROP TABLE participation');
        $this->addSql('DROP TABLE run');
        $this->addSql('DROP TABLE "user"');
    }
}
