{{- if and .Values.rustfs.enabled .Values.rustfs.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.rustfs.service.name }}
  labels:
    {{- include "api-platform.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rustfs.persistence.size }}
  {{- with .Values.rustfs.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
